### ISSUE TITLE
어떤 서비스를 만들지 토론하기

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#1]

**Comment by baesy0** [comment]
## 기준
- 사기를 꺾을 만큼 어렵지 않았으면 좋겠다.
## 아이디어
- 파비콘 만들어주기

**Comment by Cpocari** [comment]
> ## 기준
> * 사기를 꺾을 만큼 어렵지 않았으면 좋겠다.
> 
> ## 아이디어
>* 하이

**Comment by kokbee** [comment]
## 아이디어
- 파비콘을 만든다. *.png-> *.ico 파일만들기!

**Comment by soluleaf** [comment]
## 아이디어
- 단위변환을 해주는 서비스 만들기
- 자주쓰일것같은 단위 10개이내

**Comment by Cpocari** [comment]
## 기준
 
* 어렵지않게 좋은 기능으로 만든다

## 아이디어
* 타이머를 만든다
* https://vclock.kr/timer/ 대표적인 타이머 사이트
* 타이머에도 시간을 조정하거나 미세 조정하는 기능이 필요하다
* 원하는 게임 서버 시간을 나타낼수있어도 좋을 것 같다 (보스 시간표 등등)

**Comment by baesy0** [comment]
> ## 아이디어
> * 단위변환을 해주는 서비스 만들기

'단위'라는 주제는 광범위한 거 같아요. 단위 중에서도 범위를 좁혀야 할 거 같아요.

**Comment by baesy0** [comment]
일단 파비콘에 대하여 조사를 먼저 해보기로 결론이 남.
