### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#101]
rest api 짜기

**Comment by Cpocari** [comment]
https://velog.io/@kysung95/개발상식-Ajax와-Axios-그리고-fetch

Ajax and fetch 정리가 잘되어있어서 공유드립니다.

**Comment by kokbee** [comment]
<img width="689" alt="스크린샷 2021-06-27 오후 3 52 41" src="https://user-images.githubusercontent.com/44458177/123535592-c2808680-d75f-11eb-8db6-ed61e65b3dea.png">

리팩토링은 여러분의 몫

**Comment by baesy0** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/40417084/124374622-d2581780-dcd7-11eb-95f7-5a21f925ddfe.png">
https://meetup.toast.com/posts/92

**Comment by baesy0** [comment]
공유 완료
