### ISSUE TITLE
DB solution 선정하기

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#102]
DB solution 조사 및 토론하기

**Comment by baesy0** [comment]
민수님 제안: https://firebase.google.com/docs/database

**Comment by soluleaf** [comment]
해당웹기능을 사용할 유저도 정해지지않은 상황이라, 
현재규모로는 웹 로컬스토리지를 활용하는 편이 좋을것같습니다. ^^ 
추후에 필요할시기에 다시 논의하기로해용 ~

**Comment by baesy0** [comment]
[PWA에 대한 글](https://webactually.com/2017/09/28/웹-프로젝트는-pwa이어야-한다1/)을 읽다가 본문 중에 있던 내용이에요.
나중에 로컬스토리지, 세션스토리지 등에 대해 공부할 때 참고하려고 기록해둡니다:)

<img width="735" alt="image" src="https://user-images.githubusercontent.com/40417084/124710184-61af3600-df37-11eb-95de-d4c443338fa8.png">
