### ISSUE TITLE
솔잎님의 Javascript 코드 리팩토링하기

### ISSUE THREAD

**Issue by kokbee** [janghangdong-minions/lotto#103]

**Comment by soluleaf** [comment]
마음에드는 로토넘버가 나올경우 유지한채
저장리스트공간에 로토넘버를 차곡차곡저장한다. 
/
리로드를 할경우 저장되어있는 로토넘버를 유지한체 메인로토넘버만 리로드한다. 
/

**Comment by soluleaf** [comment]
1. 리로드 를 새로고침이 아닌 새로운넘버를 받아서 교체해야한다. 
2. 저장을하면, 넘버를 로컬스토리지에 저장한다.
3. 로컬스토리지에 넘버가있다면 저장리스트에 렌더한다. 
4. 각리스트 아이템 끝에 삭제버튼을 넣는다.

**Comment by baesy0** [comment]
커다란 이슈니까 세부 이슈로 나눠서 차근차근 처리하도록 합시당!
related PR: #124 
토론할 수 있는 구체적인 코드가 생겼다는 게 어썸!✨
