### ISSUE TITLE
공유: 광고 문구

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#104]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/40417084/122866269-9ed5ce80-d362-11eb-90c4-ace5eecb4d43.png">

좀 설렜다..

**Comment by kokbee** [comment]
<img width="358" alt="스크린샷 2021-06-22 오후 11 08 00" src="https://user-images.githubusercontent.com/44458177/122939605-bc308a00-d3ae-11eb-869e-5d85a8821d2d.png">

제가 공부중인 노마드 코더의 광고도 벤치마킹 !

**Comment by Cpocari** [comment]
미니언이 아닌 사람이 있어요

**Comment by baesy0** [comment]
> 미니언이 아닌 사람이 있어요

도대체 누구래! 👀

**Comment by baesy0** [comment]
공유되었으니 닫을게요!
