### ISSUE TITLE
REST API: 리팩토링

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#113]
javascript 리팩토링하기

**Comment by baesy0** [comment]
1. 새로 생긴 번호들이 버튼 아래에 생기도록 하기

**Comment by soluleaf** [comment]
/() : 로또넘버를 얻는다
/() : 로토넘버를 로컬스토리지에 저장한다
/() : 해당 로토넘버를 지운다
/)  : 로토넘버를 바꾼다
