### ISSUE TITLE
API 설계

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#127]

**Comment by baesy0** [comment]
### URL
- api/:objectname

**Comment by kokbee** [comment]
Ref: https://github.com/kakao/cite/tree/master/controller

**Comment by kokbee** [comment]
Go route 분할 및 CRUD 방식
Ref: https://pythonq.com/so/go/825881

**Comment by baesy0** [comment]
### 메소드 별로 함수 나누기
- go stdlib가 있는지 확인
- 외부 라이브러리에는 어떤 게 있는지 확인
- 스탠다드 라이브러리와 외부 라이브러리 중 어떤 게 더 좋을지 토론

**Comment by baesy0** [comment]
wiki에 정리해두기

**Comment by kokbee** [comment]
스탠다드와 프레임워크의 차이: https://juyeop.tistory.com/23

**Comment by kokbee** [comment]
go 프레임워크 

Revel: https://revel.github.io
Beego: http://beego.me
Martini: https://github.com/go-martini/martini
Gin: https://gin-gonic.github.io/gin
GoCraft: https://github.com/gocraft/web
Traffic: https://github.com/pilu/traffic
Gorilla | http://www.gorillatoolkit.org

**Comment by baesy0** [comment]
### 메소드는 항상 명시해주기(javascript)
- GET이 default이긴 하지만 그래도 명시해주기로

**Comment by baesy0** [comment]
### reference
- https://github.com/kakao/cite/tree/master/controller
- https://github.com/kakao/network-node-manager

**Comment by baesy0** [comment]
## 토론 내용 wiki에 정리함
https://github.com/janghangdong-minions/lotto/wiki/API-convention
