### ISSUE TITLE
어떤 서비스 만들지 조사

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#2]

**Comment by kokbee** [comment]
## 참고사이트
- [ConvertIO](https://convertio.co/kr/png-ico/)
- [AnyConv](https://anyconv.com/ko/png-to-ico-byeonhwangi/)
- [Png2icojs](https://png2icojs.com/kr/)
- [ConvertIco](https://convertico.com/)

**Comment by baesy0** [comment]
만든다면 가져다가 쓸만한 것들은 많은 거 같아요
## 참고 라이브러리
- https://github.com/cdujeu/crossicon

## Imagemagick
- https://imagemagick.org/index.php

## dropzone - 드래그앤드롭 기능
- https://www.dropzonejs.com

**Comment by soluleaf** [comment]
- 기준 png 지만 경쟁력을 위해 여러 포맷을 지원해야 할 수도 있을것같다.
- 적어도 자주쓰이는 jpg라도...

**Comment by kokbee** [comment]
> ## 참고 라이브러리
> * https://github.com/cdujeu/crossicon

**Comment by Cpocari** [comment]
파비콘 이미지 만들기에 대한 사이트가 많고 

생각보다 많은 기능들을 이미 갖춰놔서 경쟁력이 필요 할 것 같다.

경쟁력을 위해 특별한 기능을 찾아봐야겠다.
![gittest](https://user-images.githubusercontent.com/20947861/107357857-fbec8880-6b15-11eb-856b-870ab5309248.JPG)

**Comment by baesy0** [comment]
### 파비콘에 대한 설명 reference
https://webdir.tistory.com/337
https://github.com/audreyfeldroy/favicon-cheat-sheet

### 일주일동안 고민해본 선택의 기준
- SaaS를 만들면서 얻게 될 지식과 능력이 내가 원하는 것인가.
- 만드는 과정 자체도 공부할 거리니까, 서비스 자체는 단순한게 낫지 않을까.

**Comment by baesy0** [comment]
## 친구의 아이디어
### 아이디어
로또 번호 랜덤 생성기

### 광고
온라인 로또 구매처를 광고로 박으면 클릭확률이 높을 것

### 마케팅
어머니 아버지 세대의 단톡방에 뿌린다.

**Comment by Cpocari** [comment]
### 아이디어
닉네임 지어주기

### 광고
모든 게임 모든컨텐츠에는 닉네임을 필요로 하고 그 닉네임은 선착순이라서
많은 단어를 골라주는 시스템은 누구나 원한다!
 
### 마케팅
알아서 마케팅됨 닉네임 추천 커플닉추천 검색해보신분??

**Comment by baesy0** [comment]
### 파비콘과 비슷한 아이디어
- apple app icon generator
- https://appicon.co

**Comment by baesy0** [comment]
### 간단한 것으로 할거라면
- 단위변환
- 로또
- 주사위굴리기

**Comment by soluleaf** [comment]
### 가벼운 프로젝트로 가기위한조건 
- 인풋없이 아웃풋만 제공하기

**Comment by baesy0** [comment]
> ### 가벼운 프로젝트로 가기위한조건
> * 인풋없이 아웃풋만 제공하기

regular expression을 한 번 경험해보려면 인풋이 있으면 좋을 거 같기도 해요

**Comment by baesy0** [comment]
로또로 결정!
