### ISSUE TITLE
GO 관련 환경변수 설정하는 법 wiki에 정리해두기

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#3]

**Comment by soluleaf** [comment]
wiki 작성방법에 적응하기 어렵네요
문단나누기등 원하는데로 작성할떄까지는 시간이 소요되것군요 ㅎㅎ

**Comment by baesy0** [comment]
맞아요 마크다운 문법이 적응하고나면 엄청 편한데
적응하기까지 좀 시간이 걸려요:)
마크다운 문법에 익숙해지는 시간까지 필요할테니 솔잎님 페이스에 맞춰서 진행하면 될 거 같아요

**Comment by baesy0** [comment]
솔잎님 근데 footer로 만들었어요!ㅋㅋ
우측 상단에 있는 New Page 버튼으로 만들어주시겠어요?
<img width="350" alt="image" src="https://user-images.githubusercontent.com/40417084/109383714-895c1500-792b-11eb-90d9-f021006f071f.png">

**Comment by baesy0** [comment]
New Page로 옮기기 완료!
