### ISSUE TITLE
경쟁 SaaS조사

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#6]
로또번호 생성해주는 SaaS 사이트의 장단점 조사

**Comment by baesy0** [comment]
- 제외할 숫자 선택하는 기능
- 로또볼 수확게임
- 로또볼을 요괴로부터 지키는 게임
- 로또번호생성기로 당첨된 역대 당첨번호들
- 로또 실수령액 계산기
- 로또 1등 나왔던 판매점 리스트
- 여러 번 1등 나온 집은 상위로 올리자 by @soluleaf 
- 실시간 TV
- 연금 복권

**Comment by baesy0** [comment]
로또볼 수확게임

**Comment by baesy0** [comment]
로또볼을 요괴로부터 지키는 게임

**Comment by baesy0** [comment]
로또번호생성기로 당첨된 역대 당첨번호들

**Comment by baesy0** [comment]
로또 실수령액 계산기

**Comment by baesy0** [comment]
로또 1등 나왔던 판매점 리스트

**Comment by baesy0** [comment]
여러번 1등 나온 집은 상위로 올리자 by @soluleaf

**Comment by baesy0** [comment]
실시간 TV

**Comment by baesy0** [comment]
연금 복권

**Comment by soluleaf** [comment]
[서비스 by  펴늬 ](https://pyony.com/ebooks/)

**Comment by baesy0** [comment]
기본 기능을 완성한 후 필요할 때 다시 토의하기로!
