### ISSUE TITLE
min, max, range flag변수 예외처리 리팩토링 토의하기

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#61]
현재 구조에서는 gennum이 true일 때에만 예외처리가 일어난다.
하지만 http가 실행될 때에도 예외처리가 될 필요가 있다.
예외처리를 어디서 하는게 좋을지 토론해보기

**Comment by baesy0** [comment]
```go
else if *flagGenNum {
		if *flagRangeMin < 1 {
			fmt.Println("rmin값은 1이상 입력해주세요")
		}
		if *flagRangeMax < 45 {
			fmt.Println("rmax값은 45이상 입력해주세요")
		}
		if *flagRangeMax <= *flagRangeMin {
			fmt.Println("rmax값은 rmin값보다 큰 수를 입력해주세요")
		}
		if *flagRange < 7 {
			fmt.Println("range값을 7이상 입력해주세요")
		}
		GenRandomNums(*flagRangeMin, *flagRangeMax, *flagRange)
	}
```
위는 현재 GenRandomNums를 실행하는 부분에서 하고 있는 예외처리인데
수를 저희가 마음대로 바꿔가면서 test하려면
```go
if *flagRangeMax <= *flagRangeMin {
			fmt.Println("rmax값은 rmin값보다 큰 수를 입력해주세요")
		}
```
이 부분을 제외한 나머지 예외처리는 없어도 되지 않을까요?
어떻게 생각하세요?

**Comment by Cpocari** [comment]
45 제한은 없이 진행하나요?

**Comment by kokbee** [comment]
range 값도 없어지면 실행이 안되지않나요?

**Comment by baesy0** [comment]
> range 값도 없어지면 실행이 안되지않나요?

default값이 있어서 정해주지 않으면 7로 실행돼요!

```go
flagRange    = flag.Int("r", 7, "range for generating random numbers")
```

**Comment by baesy0** [comment]
> 45 제한은 없이 진행하나요?

default가 45니까 괜찮지 않을까요?

flag변수는 상수가 아닌 필요한 수를 넣어 조절하기 위함이니까
이 편이 좋지 않을까 싶었어요.
그러면 다양한 경우로 함수를 테스트 할 수도 있고,
로또의 규칙이 바꼈을 때 수정할 부분이 적어지기도 하구요.

**Comment by kokbee** [comment]
> > range 값도 없어지면 실행이 안되지않나요?
> 
> default값이 있어서 정해주지 않으면 7로 실행돼요!
> 
> ```go
> flagRange    = flag.Int("r", 7, "range for generating random numbers")
> ```

ㅇㅎ!

**Comment by baesy0** [comment]
```go
if *flagRange < 7 {
			fmt.Println("range값을 7이상 입력해주세요")
		}
```
이건 확실히 0이상으로 조건을 바꾸는게 좋을 거 같아요

**Comment by kokbee** [comment]
백엔드랑, 프론트엔드를 둘다 생각한 저의 의견이라서 참고만해주세용!

**Comment by baesy0** [comment]
> 백엔드랑, 프론트엔드를 둘다 생각한 저의 의견이라서 참고만해주세용!

range는 0이상이어야 한다는 조건은 꼭 필요하다는데 동의해요!
