### ISSUE TITLE
원하는 페이지 디자인있으면 레퍼런스 혹은 아이디어 달아주세요✨ 

### ISSUE THREAD

**Issue by baesy0** [janghangdong-minions/lotto#66]

**Comment by Cpocari** [comment]
단순한 번호 뽑기 기능에 충실한 디자인 , 추가기능 다양한 옵션은 숨김 펼치기로 하면 좋겠어요
번호 뽑으러왔는데 기능이 너무 복잡하면 바로 뒤로가기...각

**Comment by Cpocari** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/20947861/116804628-2a995e80-ab5b-11eb-8d4b-e6b6963075b3.png">
로또 페이지인데 로또 관련된 질문을 예상해서 적어 놨는데 좋은거같아요

**Comment by Cpocari** [comment]
테마 방식으로 추가해도 좋아보임

돼지꿈꾸면 누르는 버튼

날씨가 좋을때 누르는 버튼

비오는날 기운이 좋은 버튼 등등

짱짱한 경쟁사이트에 경쟁이되려면 우리만의 아이템이 필요함(테마 버튼)

**Comment by soluleaf** [comment]
![Uploading 스크린샷 2021-05-04 오후 7.53.18.png…]()

**Comment by baesy0** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/40417084/116993526-8f4ae980-ad12-11eb-93b2-023b6dfe78de.png">

**Comment by soluleaf** [comment]
<img width="460" alt="스크린샷 2021-05-04 오후 7 53 18" src="https://user-images.githubusercontent.com/58694798/116994929-5d3a8700-ad14-11eb-81a8-6cc4e27ebdb4.png">

**Comment by baesy0** [comment]
지속적으로 업데이트 되어야 할 이슈니까 닫아둘게요
아이디어가 있을 때 마다 댓글 달아주세요:)
